resume_from_checkpoint_path: null # only used for resume_from_checkpoint option in PL
result_path: "/store/lixumin/recognition_diagram/latex-geo-vie"
pretrained_model_name_or_path: "/store/lixumin/xizhi_OCR/nougat_ocr/pretrain_model/small_model/" # loading a pre-trained model (from moldehub or path)
dataset_name_or_paths: ["/store/lixumin/recognition_diagram/dataset/test/"] # loading datasets (from moldehub or path)
sort_json_key: False # cord dataset is preprocessed, and publicly available at https://huggingface.co/datasets/naver-clova-ix/cord-v2
train_batch_sizes: [2]
val_batch_sizes: [2]
input_size: [560, 560] # when the input resolution differs from the pre-training setting, some weights will be newly initialized (but the model training would be okay)
max_length: 512
align_long_axis: False
num_nodes: 1
seed: 42
lr: 3e-5
warmup_steps: 1500 # 200000/12/2*5/10 190000/8*10/10
num_training_samples_per_epoch: 4464
max_epochs: 5
max_steps: -1
num_workers: 4
val_check_interval: 1.0
check_val_every_n_epoch: 1
gradient_clip_val: 1.0
verbose: True